name: Build changelog

outputs:
  has_prs:
    value: ${{ steps.build_changelog.outputs.categorized_prs || steps.build_changelog.outputs.uncategorized_prs }}
  previous_version:
    value: ${{ steps.build_changelog.outputs.fromTag }}
  next_version:
    value: ${{ steps.next_version.outputs.version }}
  notes:
    value: ${{ steps.process_changelog.outputs.changelog }}
  release:
    value: ${{ steps.next_release.outputs.release }}

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5

    - run: pip install semver
      shell: bash

    - id: build_changelog
      uses: mikepenz/release-changelog-builder-action@v4
      with:
        configuration: ${{ github.action_path }}/config.json
        outputFile: NEXT.md
        toTag: HEAD

    - id: process_changelog
      run: |
        echo 'changelog<<EOF' >> $GITHUB_OUTPUT
        cat NEXT.md | python ${{ github.action_path }}/process_changelog.py >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT
      shell: bash

    - id: next_release
      run: |
        echo "release=$(cat NEXT.md | python ${{ github.action_path }}/next_release.py)" >> $GITHUB_OUTPUT
      shell: bash

    - id: next_version
      run: |
        echo "version=$(python ${{ github.action_path }}/next_version.py \
          ${{ steps.build_changelog.outputs.fromTag }} \
          ${{ steps.next_release.outputs.release }})" >> $GITHUB_OUTPUT
      shell: bash
